/**
 * Generated by scripts/generate-bootstrap-icons.mjs from bootstrap-icons 1.13.1.
 * Run `npm run icons:generate` after intentionally changing the selected icons.
 */
import type { LayerIconName } from "../core/types";

export interface EmbeddedBootstrapIconPath {
  readonly d: string;
  readonly fillRule?: "evenodd";
}

export interface EmbeddedBootstrapIconDefinition {
  readonly legacyValue: number;
  readonly bootstrapName: string;
  readonly viewBox: string;
  readonly paths: readonly EmbeddedBootstrapIconPath[];
}

export const bootstrapIconDefinitions = {
  warning: {
    legacyValue: 0,
    bootstrapName: "exclamation-lg",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M7.005 3.1a1 1 0 1 1 1.99 0l-.388 6.35a.61.61 0 0 1-1.214 0zM7 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0",
      },
    ],
  },
  success: {
    legacyValue: 1,
    bootstrapName: "check-lg",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425z",
      },
    ],
  },
  error: {
    legacyValue: 2,
    bootstrapName: "x-lg",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z",
      },
    ],
  },
  question: {
    legacyValue: 3,
    bootstrapName: "question-lg",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M4.475 5.458c-.284 0-.514-.237-.47-.517C4.28 3.24 5.576 2 7.825 2c2.25 0 3.767 1.36 3.767 3.215 0 1.344-.665 2.288-1.79 2.973-1.1.659-1.414 1.118-1.414 2.01v.03a.5.5 0 0 1-.5.5h-.77a.5.5 0 0 1-.5-.495l-.003-.2c-.043-1.221.477-2.001 1.645-2.712 1.03-.632 1.397-1.135 1.397-2.028 0-.979-.758-1.698-1.926-1.698-1.009 0-1.71.529-1.938 1.402-.066.254-.278.461-.54.461h-.777ZM7.496 14c.622 0 1.095-.474 1.095-1.09 0-.618-.473-1.092-1.095-1.092-.606 0-1.087.474-1.087 1.091S6.89 14 7.496 14",
        fillRule: "evenodd",
      },
    ],
  },
  lock: {
    legacyValue: 4,
    bootstrapName: "lock-fill",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M8 0a4 4 0 0 1 4 4v2.05a2.5 2.5 0 0 1 2 2.45v5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 13.5v-5a2.5 2.5 0 0 1 2-2.45V4a4 4 0 0 1 4-4m0 1a3 3 0 0 0-3 3v2h6V4a3 3 0 0 0-3-3",
        fillRule: "evenodd",
      },
    ],
  },
  sad: {
    legacyValue: 5,
    bootstrapName: "emoji-frown",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16",
      },
      {
        d: "M4.285 12.433a.5.5 0 0 0 .683-.183A3.5 3.5 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.5 4.5 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5m4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5",
      },
    ],
  },
  smile: {
    legacyValue: 6,
    bootstrapName: "emoji-smile",
    viewBox: "0 0 16 16",
    paths: [
      {
        d: "M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16",
      },
      {
        d: "M4.285 9.567a.5.5 0 0 1 .683.183A3.5 3.5 0 0 0 8 11.5a3.5 3.5 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5m4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5",
      },
    ],
  },
} as const satisfies Record<LayerIconName, EmbeddedBootstrapIconDefinition>;
