import type { CSSProperties } from "react";

export interface LayerTheme {
  background: string;
  foreground: string;
  muted: string;
  primary: string;
  primaryHover: string;
  primaryActive: string;
  success: string;
  warning: string;
  error: string;
  border: string;
  shade: string;
  shadow: string;
  inputBackground: string;
  inputBorder: string;
  tooltipBackground: string;
  loadingBackground: string;
  focusRing: string;
  radius: string;
  zIndex: number;
}

export type LayerThemeSelection =
  | "light"
  | "dark"
  | "system"
  | Partial<LayerTheme>;

export const lightTheme: LayerTheme = {
  background: "#ffffff",
  foreground: "#1f2937",
  muted: "#6b7280",
  primary: "#2563eb",
  primaryHover: "#1d4ed8",
  primaryActive: "#1e40af",
  success: "#16a34a",
  warning: "#d97706",
  error: "#dc2626",
  border: "#d1d5db",
  shade: "#000000",
  shadow: "0 18px 55px rgba(15, 23, 42, 0.28)",
  inputBackground: "#ffffff",
  inputBorder: "#9ca3af",
  tooltipBackground: "#111827",
  loadingBackground: "#2d3748",
  focusRing: "#60a5fa",
  radius: "12px",
  zIndex: 19891014,
};

export const darkTheme: LayerTheme = {
  ...lightTheme,
  background: "#172033",
  foreground: "#f3f4f6",
  muted: "#aeb8c8",
  primary: "#60a5fa",
  primaryHover: "#93c5fd",
  primaryActive: "#3b82f6",
  border: "#475569",
  shade: "#020617",
  shadow: "0 20px 60px rgba(0, 0, 0, 0.6)",
  inputBackground: "#0f172a",
  inputBorder: "#64748b",
  tooltipBackground: "#020617",
  loadingBackground: "#111827",
  focusRing: "#93c5fd",
};

export const resolveTheme = (
  selection: LayerThemeSelection | undefined,
  prefersDark: boolean
): LayerTheme => {
  if (!selection || selection === "light") {
    return lightTheme;
  }
  if (selection === "dark" || (selection === "system" && prefersDark)) {
    return darkTheme;
  }
  if (selection === "system") {
    return lightTheme;
  }
  return { ...lightTheme, ...selection };
};

/** @deprecated styled-components now owns runtime styles. */
export const layerStyles =
  "/* layer-esm styles are generated by styled-components at runtime. */";

export const styleObjectToCssText = (style: CSSProperties): string =>
  Object.entries(style)
    .filter(([, value]) => value !== undefined && value !== null)
    .map(([property, value]) => {
      const cssProperty = property.replace(
        /[A-Z]/g,
        (letter) => `-${letter.toLowerCase()}`
      );
      return `${cssProperty}:${String(value)}`;
    })
    .join(";");
