import layer, {
  alert,
  close,
  closeAll,
  config,
  confirm,
  destroy,
  full,
  getChildFrame,
  getFrameIndex,
  iframeAuto,
  iframeSrc,
  load,
  min,
  msg,
  open,
  prompt,
  ready,
  restore,
  setTop,
  style,
  tab,
  tips,
  title,
} from "./core/layer";
import type {
  LayerArea,
  LayerConfigOptions,
  LayerIcon,
  LayerIconName,
  LayerOffset,
  LayerOffsetKeyword,
  LayerOptions,
  LayerPromptOptions,
  LayerShade,
  LayerStyleOptions,
  LayerTabItem,
  LayerTabOptions,
  LayerTipDirection,
  LayerTipsOptions,
  LayerTitle,
  LayerType,
} from "./core/types";
import { darkTheme, layerStyles, lightTheme } from "./styles/theme";
import type { LayerTheme, LayerThemeSelection } from "./styles/theme";

export { darkTheme, layerStyles, lightTheme };

export default layer;

export type {
  LayerArea,
  LayerConfigOptions,
  LayerIcon,
  LayerIconName,
  LayerOffset,
  LayerOffsetKeyword,
  LayerOptions,
  LayerPromptOptions,
  LayerShade,
  LayerStyleOptions,
  LayerTabItem,
  LayerTabOptions,
  LayerTipDirection,
  LayerTipsOptions,
  LayerTitle,
  LayerType,
  LayerTheme,
  LayerThemeSelection,
};

export {
  alert,
  close,
  closeAll,
  config,
  confirm,
  destroy,
  full,
  getChildFrame,
  getFrameIndex,
  iframeAuto,
  iframeSrc,
  load,
  min,
  msg,
  open,
  prompt,
  ready,
  restore,
  setTop,
  style,
  tab,
  tips,
  title,
};
